<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'blobfolio\\wp\\looksee\\about' => '/blobfolio/wp/looksee/about.php',
                'blobfolio\\wp\\looksee\\admin' => '/blobfolio/wp/looksee/admin.php',
                'blobfolio\\wp\\looksee\\ajax' => '/blobfolio/wp/looksee/ajax.php',
                'blobfolio\\wp\\looksee\\cli' => '/blobfolio/wp/looksee/cli.php',
                'blobfolio\\wp\\looksee\\cli\\checksums' => '/blobfolio/wp/looksee/cli/checksums.php',
                'blobfolio\\wp\\looksee\\cli\\scan' => '/blobfolio/wp/looksee/cli/scan.php',
                'blobfolio\\wp\\looksee\\core' => '/blobfolio/wp/looksee/core.php',
                'blobfolio\\wp\\looksee\\cron' => '/blobfolio/wp/looksee/cron.php',
                'blobfolio\\wp\\looksee\\db' => '/blobfolio/wp/looksee/db.php',
                'blobfolio\\wp\\looksee\\files' => '/blobfolio/wp/looksee/files.php',
                'blobfolio\\wp\\looksee\\license' => '/blobfolio/wp/looksee/license.php',
                'blobfolio\\wp\\looksee\\options' => '/blobfolio/wp/looksee/options.php',
                'blobfolio\\wp\\looksee\\scan' => '/blobfolio/wp/looksee/scan.php',
                'blobfolio\\wp\\looksee\\vendor\\common\\bc' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/bc.php',
                'blobfolio\\wp\\looksee\\vendor\\common\\cast' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/cast.php',
                'blobfolio\\wp\\looksee\\vendor\\common\\cli' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/cli.php',
                'blobfolio\\wp\\looksee\\vendor\\common\\constants' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/constants.php',
                'blobfolio\\wp\\looksee\\vendor\\common\\data' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/data.php',
                'blobfolio\\wp\\looksee\\vendor\\common\\dom' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/dom.php',
                'blobfolio\\wp\\looksee\\vendor\\common\\file' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/file.php',
                'blobfolio\\wp\\looksee\\vendor\\common\\format' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/format.php',
                'blobfolio\\wp\\looksee\\vendor\\common\\mb' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/mb.php',
                'blobfolio\\wp\\looksee\\vendor\\common\\mime' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/mime.php',
                'blobfolio\\wp\\looksee\\vendor\\common\\ref\\cast' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/ref/cast.php',
                'blobfolio\\wp\\looksee\\vendor\\common\\ref\\cast_base' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/ref/cast_base.php',
                'blobfolio\\wp\\looksee\\vendor\\common\\ref\\cast_full' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/ref/cast_full.php',
                'blobfolio\\wp\\looksee\\vendor\\common\\ref\\file' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/ref/file.php',
                'blobfolio\\wp\\looksee\\vendor\\common\\ref\\format' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/ref/format.php',
                'blobfolio\\wp\\looksee\\vendor\\common\\ref\\mb' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/ref/mb.php',
                'blobfolio\\wp\\looksee\\vendor\\common\\ref\\sanitize' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/ref/sanitize.php',
                'blobfolio\\wp\\looksee\\vendor\\common\\sanitize' => '/vendor/blobfolio/blob-common/lib/blobfolio/common/sanitize.php',
                'blobfolio\\wp\\looksee\\vendor\\domain\\data' => '/vendor/blobfolio/blob-domain/lib/blobfolio/domain/data.php',
                'blobfolio\\wp\\looksee\\vendor\\domain\\domain' => '/vendor/blobfolio/blob-domain/lib/blobfolio/domain/domain.php',
                'blobfolio\\wp\\looksee\\vendor\\mimes\\data' => '/vendor/blobfolio/blob-mimes/lib/blobfolio/mimes/data.php',
                'blobfolio\\wp\\looksee\\vendor\\mimes\\mimes' => '/vendor/blobfolio/blob-mimes/lib/blobfolio/mimes/mimes.php'
            );
        }
        if (isset($classes[$class])) {
            require __DIR__ . $classes[$class];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
